---
title: "Project 2 - Example Main Script"
author: "Xiangyu Liu"
date: "February 2, 2018"
output:
  pdf_document: default
  html_document: default
---
## STEP0: Prepare and load the library
```{r}
if(!require("EBImage")){
  source("https://bioconductor.org/biocLite.R")
  biocLite("EBImage")
}

if(!require("gbm")){
  install.packages("gbm")
}

if(!require("pbapply")){
  install.packages("pbapply")
}
if(!require("rlang")){
  install.packages("rlang")
}
library("EBImage")
library("gbm")
library("tidyverse")
```
##set the working directory
```{r}
# setwd("/Users/pinkysilva/Documents/GitHub/project-2-predictive-modelling-group4/doc") 
# Replace the above with your own path or manually set it in RStudio to where the main.rmd file is located. 
```
##set the directory for the training set and test set
```{r}
img_train_dir  <- "../data/pets/train/"  ##This is where I put the training data

img_test_dir   <- "../data/pets/test/"  ##This is where I put the test data
```
##read the labels of traing data
```{r}
labels = read_csv(paste(img_train_dir, '../train_label.txt', sep=''), col_names = c('label'))
#we are making 6 times as many features from the images by transforming them
expanded_labels <- list()
for (i in 1:nrow(labels))
  for(j in 1:6)
    expanded_labels <- rbind(expanded_labels, labels[i,])

```

```{r}
n_files <- length(list.files(img_train_dir))
n_files
```
There are 2000 images in the training set. Then we will read in all the images and store their dimensions in the `dat` matrix.
```{r}
n_files <- 2000
dat <- matrix(NA, nrow = n_files, ncol = 3) 
imgs <- vector("list", n_files)

for(i in 1:n_files){
  img <- readImage(paste0(img_train_dir, "pet", i, ".jpg"))
  imgs[[i]] <- img
  dat[i, 1:length(dim(img))] <- dim(img)
}
head(dat)
```

## get the general information of the images
```{r}
# How many B/W images?  All color.
table(dat[, 3])
# How many rows in each image?
table(dat[, 1])
```
##resize the image
```{r}
img_resized = pblapply(imgs, function(img) { resize(img, 128, 128) })
img_resized = pblapply(img_resized, function(img){channel(img, "gray")})
dim(img_resized[[1]])
length(img_resized)
```
##construct visual features
```{r}
feature1 <- function(img_list, data_name, export=T){
  
  ### Construct process features for training/testing images
  ### Sample simple feature: Extract row average raw pixel values as features
  
  ### Input: List of scaled images
  ### Output: an .RData file contains processed features for the images
  
  ### load libraries
  library("EBImage")
  
  dat <-data.frame()
  
  for(i in 1:length(img_list)){
#    img     <- readImage(paste0(img_dir, data_name, i, ".jpg"))
    mean    <- rowMeans(img_list[[i]])
  
    
    img_rotate <- translate(rotate(img_list[[i]], 45), c(50, 0)) #rotate 45 degrees clockwise
    mean_rotate1 <- rowMeans(img_rotate)
    img_rotate <- translate(rotate(img_list[[i]],-45), c(50, 0)) #rotate 45 degrees ccw
    mean_rotate2 <- rowMeans(img_rotate)
    img_flip   <- flip(img_list[[i]])
    mean_flip <- rowMeans(img_rotate)
    img_flop    <- flop(img_list[[i]])
    mean_flop <- rowMeans(img_rotate)
    img_flipflop <- flop(flip(img_list[[i]]))
    mean_flipflop <- rowMeans(img_rotate)
    dat = rbind(dat, mean, mean_rotate1, mean_rotate2, mean_flip, mean_flop, mean_flipflop)
  }
  
  colnames(dat) <- c(1:181)

  ### output constructed features
  if(export){
    save(dat, file = paste0("../output/feature_", data_name, ".Rdata"))
  }
  return(dat)
}
```

```{r}
source("../lib/feature.R")
run.feature.train <- TRUE # process features for training set

run.feature.test  <- TRUE # process features for test set

tm_feature_train <- NA

if(run.feature.train){
  tm_feature_train <- system.time(dat_train <- feature1(img_resized, data_name = "train", export = TRUE))
}

tm_feature_train

#add labels as the final column in the dataframe
dat_train <- cbind(dat_train, expanded_labels)
dat_test <- dat_train[10000:12000,]
dat_train <- dat_train[-c(10000:12000),]

dat_train

dat_train[,182] <- ifelse(dat_train[,182] == 'dog', 1, 0)
tm_feature_test <- NA
write.csv(dat_train, 'dat_train.csv')
#if(run.feature.test){
#  tm_feature_test <- system.time(dat_test <- feature(img_test_dir, "test", 
#                                                     data_name = "pets", export = TRUE))
#}

```

```{r}
library(glmnet)
x <- read.csv('feature_list.csv', header = FALSE)
x<-x[,2:2001]
x<-x[2:784,]

x<-data.matrix(x)
x1<-head(x)
x1
x <- x[,-1]
dim(x)
head(x)
y <- t(x)
label_factor <- ifelse(label == 'dog', 1, 0)
label_factor

y
x<-data.matrix(x)
a<-x[,1:181]
b<-x[,182]
logreg<-glmnet(y,label_factor, family='binomial')
prediction=predict(logreg,y,type='class', s= logreg$lambda[length(logreg$lambda)])
mean(prediction==label_factor)
length(which(prediction==0))
```

